### ISSUE TITLE
$_X_font="vga11x19" doesn't work

### ISSUE THREAD

**Issue by bpranoto** [stsp/dosemu2#323]
Setting $_X_font="vga11x19" in /etc/dosemu/dosemu.conf doesn't work.

_You do not have the DOSEMU vga11x19 font installed and are running
remote X. You need to install the vga11x19 font on your _local_ Xserver.
Look at the readme for details. For now we start with the bitmapped
built-in font instead, which may be slower._

**Comment by stsp** [comment]
Should now work.

**Comment by bpranoto** [comment]
Unfortunately no.

I recompiling and reinstalling dosemu2 from scratch, but there is no directory /usr/local/share/dosemu/Xfonts created as in dosemu1. Thus setting $_X_font="vga11x19" in /etc/dosemu/dosemu.conf still doesn't work

**Comment by bpranoto** [comment]
Furthermore, I manually create and set /usr/local/share/dosemu/Xfonts

Now, with $_X_font="vga11x19", dosemu just shows blackscreen.

**Comment by severach** [comment]
I see the Xfont files in the Package Contents of the old [dosemu](https://www.archlinux.org/packages/community/x86_64/dosemu/). The PKGBUILD has no special commands for installing the fonts.

I see the .bdf files in [etc/](../tree/devel/etc) but nothing is compiling or installing them to the Xfont dir. Were they deprecated?

**Comment by stsp** [comment]
OK, indeed the installation of fonts is broken too.
It worked for me because I had them installed by
some older versions...

> I see the .bdf files in etc/ but nothing is compiling or installing them to the Xfont dir.
> Were they deprecated?

Not yet, just forgotten to "port" to dosemu2.
Of course we likely should be deprecating them
in the future, when we move to SDL_ttf font rendering.
But for now it would be good to get this fixed.

**Comment by stsp** [comment]
If anyone wants to fix this, that would be very welcome.
I don't think I'll get to this within a couple of days.

**Comment by bpranoto** [comment]
is the problem related to [https://github.com/stsp/dosemu2/issues/4](url) ?

**Comment by stsp** [comment]
In those days I was only starting to write
the new code for dosemu2, so #4 is a big
mess. The code just didn't work, but poor
testers were brave. :) I think such an ancient
tickets are not relevant, and they contain too
many back-n-forth changes.

This bug is about the fonts not being generated
and installed. Its not about crashes. I think
some makefile tweak can fix this.

**Comment by bpranoto** [comment]
I got the fonts generated from dosemu1 installation.

dosemu2 seems picking the fonts right, but then it does not boot but just shows a black screen.

See the screenshot here: https://drive.google.com/file/d/0B2KmduxNHH1TNEt0OVluTlZuS1E/view?usp=sharing

boot.log (with -D N) shows dosemu using the font

```
X: X_init
X: visual class is TrueColor
X: using true color visual
X: pixel size is 32 bits/pixel
X: MIT-SHM major opcode: 130
X: using MIT-SHM
X: X_keymap_init: X server vendor is "The X.Org Foundation"
X: X_keymap_init: using DOSEMU's internal keycode translation
X: X_init: parent window: 0xd4
X: X_init: screen = 0, root = 0xd4, mainwindow = 0x2e00001
X: Using font "vga11x19", size = 11 x 19

```

...and here is the last of boot.log

```
X: X_setmode: video_mode 0x3 (TEXT), size 80 x 25 (720 x 400 pixel)
Resizing our window to 880x475 image
X: X_setmode: video_mode 0x3 (TEXT), size 80 x 25 (720 x 400 pixel)
Resizing our window to 880x475 image
X: refresh_text_palette: 0 (0 -> 0)
X: refresh_text_palette: 1 (0 -> 168)
X: refresh_text_palette: 2 (0 -> 43008)
X: refresh_text_palette: 3 (0 -> 43176)
X: refresh_text_palette: 4 (0 -> 11010048)
X: refresh_text_palette: 5 (0 -> 11010216)
X: refresh_text_palette: 6 (0 -> 11031552)
X: refresh_text_palette: 7 (0 -> 11053224)
X: refresh_text_palette: 8 (0 -> 5526612)
X: refresh_text_palette: 9 (0 -> 5526780)
X: refresh_text_palette: 10 (0 -> 5569620)
X: refresh_text_palette: 11 (0 -> 5569788)
X: refresh_text_palette: 12 (0 -> 16536660)
X: refresh_text_palette: 13 (0 -> 16536828)
X: refresh_text_palette: 14 (0 -> 16579668)
X: refresh_text_palette: 15 (0 -> 16579836)
X: unknown event 21
X: resize_ximage 880 x 475 --> 720 x 400
X: resize_ximage 720 x 400 --> 880 x 475
X: window mapped
X: expose event
X: focus in
X: unknown event 11

```

**Comment by stsp** [comment]
Are you building w/o sdl or what?

**Comment by bpranoto** [comment]
This is last lines of config.status

```
configure:7204: result: Enabling plugins:
        kbd_unicode
        ladspa
        libao
        commands
        sdl
        term
        modemu
        translate
        translate/charsets
        fluidsynth
        console
        alsa
        gpm
        X
        midimisc
        extra_charsets

```

So, I guess I build with sdl

**Comment by stsp** [comment]
Could you try `dosemu -X`, `dosemu -S`?

**Comment by stsp** [comment]
Installation is now fixed.

**Comment by stsp** [comment]
> So, I guess I build with sdl

But your log says you use X, not sdl.

**Comment by severach** [comment]
I see the Xfont files now.

I looked through my log and can't find anything that says SDL or X.

**Comment by bpranoto** [comment]
Installation fixed now, Xfonts directory created.

With `$_X_font = "vga11x19"` in /etc/dosemu/dosemu.conf

dosemu -X => Only shows black screen.
dosemu -S => Ok.

dosemu without parameter also shows black screen, I guess it is defaulted to -X. How to make it's defaulted to -S ?

**Comment by stsp** [comment]
> I looked through my log and can't find anything that says SDL or X.

You need -D+v log and even then I find it
hard to find out what frontend is used. I'll
fix that.

**Comment by stsp** [comment]
> dosemu without parameter also shows black screen,
> I guess it is defaulted to -X. How to make it's defaulted to -S ?

By disabling $_X_font... SDL is not good for pcf fonts,
dosemu uses a crude hack that loads an X plugin and it
renders fonts while SDL is only used when you switch to
gfx mode. With such a hack I thought it would be good to
keep X by default when $_X_font is used until we have a
proper rendering with SDL_ttf.

**Comment by stsp** [comment]
Silly bug... should now be fixed.

**Comment by bpranoto** [comment]
Confirmed, it's fixed now. Thanks.

I can log to my netware server now. However, when execute command: DIR, I feel the screen drawing is slower than dosemu1 in 32bit linux.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by bpranoto** [comment]
Yes. Feel as good as the old dosemu1 in 32bit. Thanks.
