### ISSUE TITLE
'dosemu -t' crashed on screen tmux

### ISSUE THREAD

**Issue by fhanzlik** [stsp/dosemu2#351]
when I run 'dosemu -t' on remote machine (accessed via ssh which run screen terminal multiplex), it crashes at start, displayed:
```
$ dosemu -t
ERROR: Fault in dosemu code, in_dpmi=0
ERROR: cpu exception in dosemu code outside of VM86()!
trapno: 0x0e  errorcode: 0x00000004  cr2: 0x04000000
eip: 0x30f10801ac  esp: 0x7fffef348dd8  eflags: 0x00010206
cs: 0x0033  ds: 0x0000  es: 0x0000  ss: 0x0000
fs: 0x0000  gs: 0x0000
fsbase: 0x7f80a1b96740 gsbase: (nil)

ERROR: Please install gdb, update dosemu from git, compile it with debug
info and report with the contents of ~/.dosemu/boot.log at
https://github.com/stsp/dosemu2/issues

ERROR: Fault handler re-entered! signal=11 _trapno=0xE
```
When i log over ssh to same machine (Fedora 19 x86_64/kernel-3.14.27) without screen, it
works - but dosemu display several errors/warnings:

```

$ dosemu -t
ERROR: Failed to load plugin /usr/lib64/ao/plugins-4/libalsa.so => dlopen() failed
ALSA lib confmisc.c:768:(parse_card) cannot find card '0'
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_card_driver returned error: No such file or directory
ALSA lib confmisc.c:392:(snd_func_concat) error evaluating strings
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_concat returned error: No such file or directory
ALSA lib confmisc.c:1251:(snd_func_refer) error evaluating name
ALSA lib conf.c:4248:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4727:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM default
ERROR: SDL sound init failed: ALSA: Couldn't open audio device: No such file or directory
ERROR: Your fluidsynth is too old and soundfonts not found
ERROR: alsa_midi (ALSA lib): seq_hw.c:457:(snd_seq_hw_open) : Permission denied open /dev/snd/seq failed
```

should I send something more detailed?

**Comment by fhanzlik** [comment]
errors in second case are solved by setting "$_sound = (off)" in dosemu.conf (this machine has not audio card) - but dosemu maybe should detect it better.

**Comment by fhanzlik** [comment]
Attached is boot.log file with some debug infos

[boot.log-f19-64.zip](https://github.com/stsp/dosemu2/files/888325/boot.log-f19-64.zip)

**Comment by fhanzlik** [comment]
"dosemu -X" and "dosemu -S" are working still well, even when dosemu run from screen session
(connect to remote machine with "ssh -X -t REMOTE screen").

terminal window, from wich "dosemu -t" run, seems be same with or without screen, and terminal setting displayed by stty are same:
```
$ stty -a
speed 38400 baud; rows 41; columns 120; line = 0;
intr = ^C; quit = ^\; erase = ^?; kill = ^U; eof = ^D; eol = M-^?; eol2 = M-^?; swtch = <undef>; start = ^Q; stop = ^S;
susp = ^Z; rprnt = ^R; werase = ^W; lnext = ^V; flush = ^O; min = 1; time = 0;
-parenb -parodd cs8 -hupcl -cstopb cread -clocal -crtscts
-ignbrk -brkint -ignpar -parmrk -inpck -istrip -inlcr -igncr icrnl -ixon -ixoff -iuclc ixany imaxbel -iutf8
opost -olcuc -ocrnl onlcr -onocr -onlret -ofill -ofdel nl0 cr0 tab0 bs0 vt0 ff0
isig icanon iexten echo echoe echok -echonl -noflsh -xcase -tostop -echoprt echoctl echoke
```

**Comment by stsp** [comment]
A slang bug that is already fixed:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=837868
Can we deal with this somehow differently?
I understand your desire to run dosemu2 on
something very old, but I am afraid we can't
support the environment as old as this.

**Comment by fhanzlik** [comment]
IMO three years old system isn't "very old". When it isn't dosemu bug, then it is OK. In real case dosemu will not be run there in screen session - then it is fine. And when it will needed, is perhaps possible upgrade slang (now it is version2.2.4).

Regarding to Your statement - please what is your opinion about running dosemu2 at some Long Term Supported (still now and several next years) distros? For me is interesting e.g. Centos 6, supported until end of 2020 year?

**Comment by fhanzlik** [comment]
btw, this crash occured also on quite actual Fedora 25/i686 with slang-2.3.0-7 :
[boot.log-f25-i686.zip](https://github.com/stsp/dosemu2/files/888361/boot.log-f25-i686.zip)

**Comment by stsp** [comment]
But I can't reproduce this on fedora-25.
Could you please do the following:
set `$_cpu_vm = "emulated"`, `$_cpu_emu = "vm86sim"`
Then run:
`valgrind --trace-children=yes --track-origins=yes dosemu -t`
and paste the output here.

**Comment by fhanzlik** [comment]
Hmm, Fedora 25 (latest) still use unpatched slang version - when I build simple testing program from Debian report which You referenced, this still crashed, equally as on Debian list.

**Comment by stsp** [comment]
Here's the fix:
https://github.com/hankem/S-Lang/commit/8b20546f61f00b47f237eff9d2d36786898085ba
But I wonder why it doesn't crash for me.

**Comment by fhanzlik** [comment]
here it is. When run under valgrind, dosemu not crashes. Note I run it on Fedora25 32-bit system.

[dosemu-valgrind-allPIDs.zip](https://github.com/stsp/dosemu2/files/888401/dosemu-valgrind-allPIDs.zip)

**Comment by fhanzlik** [comment]
and its boot.log
[boot.log-f25-i686-under_screen.zip](https://github.com/stsp/dosemu2/files/888406/boot.log-f25-i686-under_screen.zip)

**Comment by fhanzlik** [comment]
Thanks, IMHO it is possible definitively close this issue, as it isn't dosemu bug.

**Comment by stsp** [comment]
OK, closing then.
