### ISSUE TITLE
DPMI linear allocations broken

### ISSUE THREAD

**Issue by stsp** [stsp/dosemu2#385]
Linear allocations usually go to small
addresses, like 0x400000.
Currently the DPMI memory is allocated
above the DOS memory by default, making
such offsets always occupied.
Plus there was a bug that `$_dpmi_base`
was unix address. I just changed it to be DOS
address, so now by setting `$_dpmi_base`
to 0x10000000 or 0x1000000 or alike, the
problem can be avoided.
@jschwartzenberg can you check that?

Still it would be good to have this working
by default. So either to revert the patch that
makes the allocation contiguous, or to reserve
some hole...

**Comment by jschwartzenberg** [comment]
It seems that the behaviour on 32-bit and 64-bit systems is consistent now. On my older Debian Wheezy system, I can't get Quake 2 to load either, it shows the same message.

On both my 32-bit systems, 1.4.0 gives a segfault when trying to run Quake 2. Do you know from which commit it starts to make sense to test? I'm on kernel version 3.16. Maybe that's still too new?

**Comment by stsp** [comment]
What is consistent?
Let me guess.

Before the recent changes:
- error on both 64 and 32
- with non-default `$_dpmi_base` no error on 32bit but still an error on 64

Currently:
- error on both 64 and 32
- with non-default `$_dpmi_base` no error on both

Is this understanding correct?

**Comment by jschwartzenberg** [comment]
Yes, that exactly what I see.

**Comment by stsp** [comment]
So the problem is in this patch:
https://github.com/stsp/dosemu2/commit/3abb287f833ba8f04d9d50a081a3c2dd018889d3
I hated it from the very beginning and wanted
to revert it in this thread:
https://github.com/stsp/dosemu2/pull/198#issuecomment-230181509
but it seems like kvm_base didn't actually need
to get it reverted, so its still there.

This time it will likely survive too, because I
have a better idea: we can have 2 mem regions
for DPMI, one adjacent to mem_base by default
and controlled by `$_dpmi_base` as it is now, and
another one allocated with the minimum possible
gap, as it was before 3abb287. So we can have
both 3abb287 and its revert going together. :)
The adjacent region will be used for the fixed-addr
linear allocations and the non-adjacent will be used
for the normal allocations and for the non-fixed-addr
linear allocations.
This technique can work surprisingly well, namely,
the allocations to `0x400000` that are needed for
win32 apps, will always be available! Something
for which wine folks wrote a custom ld.so preloader.
And we will get that for free, thanks to Bart's glorious
ldt offset hack for non-zero mem base. I am sure
the wine folks will never think of the possibility of
adding the relocation offset to the base of all ldt
descriptors, hence making an extra level of address
translation, and of course we won't hint them. :)

**Comment by jschwartzenberg** [comment]
Hehe, it'll be interesting to see the code working! I've been involved a bit with Wine development and I know they are especially interested in DOSEMU as it's more aligned with their goals than DOSBox (no CPU emulation), so they'll definitely take a peak when people start to run Win32 commands line apps in DOSEMU2 :)
Both complement each other well now as I had to run the Quake 2 installer in Wine to get the files out and DOSEMU2 is a nice platform for running Windows 3.1 for Wine's win16 test set.

**Comment by stsp** [comment]
Why command-line apps?
AFAIK hx extender allows GUI apps too.
So does the installed quake now work under HX?
You can also try under pcem+hdpmi+hx

**Comment by jschwartzenberg** [comment]
Yeah that's true. I expect compatibility with command-line apps to be close to 100% though.
I couldn't run Quake 2 in DOSEMU yet. There is no visible error but it still doesn't start. I'll try it in PCEM.

**Comment by stsp** [comment]
@bartoldeman a question: you made it so that
if vm86() is used, dpmi memory is never allocated
adjacently to lowmem. I can't quite remember your
reasoning for this, and the changelog doesn't tell
me either (we all need to write better changelongs,
yes). But I can vaguely remember this had something
to do with the fixed address of an elf interpreter or
something like that...
These days I build dosemu2 with -fpie, so is the
original reasoning still stay? And if so, what was
it exactly?
I want to undo that logic so that we can have an
adjacent region even in vm86() case, because the
win32 binaries wants to be mapped to 4Mb.

**Comment by stsp** [comment]
In other words, does the above patch look good?

**Comment by stsp** [comment]
I added the completely untested fix.
Now we have 2 separate memory areas for dpmi.
@jschwartzenberg could you please check
if hx now work with both default and non-default
$_dpmi_base?

**Comment by stsp** [comment]
I tried quake2 now, and its f$$$ing damn
awesome! So fast, so good sound sync
with video, flawless! hx rulez. :)
You need to set `$_ignore_djgpp_null_derefs = (off)`
to get it working. I'll see about making it
to work by default, should not be difficult
at all.

**Comment by andrewbird** [comment]
Pretty sure this new error message is connected to this, otherwise I'll open a new ticket?
~~~
ERROR: MAPPING: cannot find mem hole for DPMI pool
~~~
Seen on 32 bit, default dosemu.conf, no vm86() enabled on system

**Comment by andrewbird** [comment]
On occasions Dosemu fails to start up too
~~~
ERROR: Using CPU emulation because vm.mmap_min_addr > 0                         
You can most likely avoid this problem by running                               
sysctl -w vm.mmap_min_addr=0                                                    
as root, or by changing the vm.mmap_min_addr setting in                         
/etc/sysctl.conf or a file in /etc/sysctl.d/ to 0.                              
If this doesn't help, disable selinux in /etc/selinux/config                    
Conventional memory mapped from 0xb22fe000 to 0xaf927000                        
CONF: reserving 8256Kb at 0x100000 for 'x' (Extended memory (HMA+XMS))          
VID: initializing video sdl                                                     
VID: SDL plugin initialization completed                                        
Registering HWRAM, type=e base=0xad82d000 size=0x400000                         
CONF: reserving 4096Kb at 0xAD82D000 for 'e' (VGAEMU LFB)                       
CONF: reserving 12Kb at 0xC0000 for 'V' (VGAEMU Video BIOS)                     
SERIAL $Id$                                                                     
Your fluidsynth is too old                                                      
ERROR: Your fluidsynth is too old and soundfonts not found                      
ERROR: alsa_midi (ALSA lib): rawmidi_hw.c:233:(snd_rawmidi_hw_open) : No such file or directory open /dev/snd/midiC0D0 failed
ERROR: vde_switch failed: sh: 1: vde_switch: not found                          
                                                                                
PKT: Cannot run VDE (auto)                                                      
CONF: reserving 16Kb at 0xE0000 for 'E' (EMS page frame)                        
CONF: reserving 16Kb at 0xE4000 for 'E' (EMS page frame)                        
CONF: reserving 16Kb at 0xE8000 for 'E' (EMS page frame)                        
CONF: reserving 16Kb at 0xEC000 for 'E' (EMS page frame)                        
CONF: reserving 116Kb at 0xC3000 for 'U' (Upper Memory Block (UMB, XMS 3.0))    
CONF: reserving 16Kb at 0xF0000 for 'U' (Upper Memory Block (UMB, XMS 3.0))     
ERROR: MAPPING: cannot create mem pool for DPMI                                 
leavedos(dpmi_setup:3033|2) called - shutting down                              
ERROR: DPMI: can't allocate memory for DPMI host helper code                    
CONF: detected layout is "uk"                                                   
CONF: detected alternate layout: fr-latin1                                      
Enabling sigaltstack() work-around                                              
Leaving DOS before booting                                                      
leavedos(main:395|0) called - shutting down                                     
TIME: using 9154 usec for updating ALRM timer                                   
leavedos(main:420|99) called - shutting down                                    
~~~

If start it again it succeeds. The fault seems random.

**Comment by jschwartzenberg** [comment]
I currently can't start dosemu at all with my default installation. I just get this message (and the window flashes by):
> ERROR: general protection at 0x4011386f: 0

With another installation, it loads but gives bad exe messages for the internal tools. I'm not really sure what's going on.

**Comment by stsp** [comment]
@jschwartzenberg could you please check now?

**Comment by stsp** [comment]
@andrewbird I added more logging, could you
please retry? In fact I guess the problem is
because I forgot about the top-down mmap
allocations which prevents me from using the
mem hole lookups.

**Comment by stsp** [comment]
Should now be fixed, could you check?

**Comment by andrewbird** [comment]
I no longer see the error message, and as yet it hasn't failed to start, so it appears fixed. Thanks.

**Comment by stsp** [comment]
So now as we support quake2, I think
we really need some kind of the launcher
that can download games and run them.
Does anyone know if there is something
like this exists to re-use?

**Comment by jschwartzenberg** [comment]
There's a package manager tool listed on the FreeDOS website. I think it would be nice to have that working out of the box in dosemu at some point.
HX could probably be included in the default (Free)DOS installations and possibly even enabled so that win32 applications will just work.

It would also be an option to use the distribution's package manager and have repositories with dos programs in them, all set up to run inside dosemu.

For now I created my own scripts to download and install things repetitively.

**Comment by jschwartzenberg** [comment]
Which version/archive of HX do you use btw? It seems my version is still broken or broken in general.

**Comment by stsp** [comment]
> There's a package manager tool listed on the FreeDOS website.

It doesn't install random DOS games from internet,
or does it?

> HX could probably be included in the default (Free)DOS installations
> and possibly even enabled so that win32 applications will just work.

I am thinking about this too, but am not sure.
Depends on how many people wants that, perhaps.

> It would also be an option to use the distribution's package manager
> and have repositories with dos programs in them, all set up to run inside dosemu.

No, I think we just need some custom launcher to
handle 1-2 abandonware sites. I think it makes sense
to package only the bare minimum (freedos, maybe HX)
where license is good.

> For now I created my own scripts to download and install things repetitively.

I am not sure if the install process should be
similar with the one of freedos. freedos should
go to the permanent dosemu drive, while the
random games should go somewhere to /tmp,
or even being played directly from archives.

> Which version/archive of HX do you use btw?

The one that is provided at SF under a weird name
"hx-dos" (obviously not original Japheth's project).

**Comment by stsp** [comment]
Eric (who never replies to the thread), please
get hx here:
https://sourceforge.net/projects/hx-dos/
Not sure who called the project "hx-dos".

> People who can use DOS can download games manually :-)

... or use dosbox. I think dosemu1 did a lot of things
to distract users, so lets try to attract them back. :)

**Comment by jschwartzenberg** [comment]
>> There's a package manager tool listed on the FreeDOS website.

> It doesn't install random DOS games from internet,
> or does it?

Maybe they could be packaged for it. Especially if they are shareware/demo versions like Quake 2, I guess it's no problem.


I once created RPM spec files which would install a dos game under /usr/share and put a script to run it in dosemu in /usr/bin. This script would link all the game files to /tmp/game-username and make sure any score files and save files would end up in $HOME/.game. Then it would run dosemu with the game. After it was finished, it would clean up everything in /tmp. It worked quite well and I still imagine it would be possible to fill a yum repo with dos games in such a way that can be easily installed and ran.
