### ISSUE TITLE
Intermitten crash

### ISSUE THREAD

**Issue by bpranoto** [stsp/dosemu2#671]
**Describe the bug**
Sometimes dosemu2 crashes while running Multi Edit for DOS

**To Reproduce**
Intermitten crash, cannot reproduce on purpose

**Expected behavior**
No crash

**Attach the log**
It is located in ~/.dosemu/boot.log
[boot.log](https://github.com/stsp/dosemu2/files/2363995/boot.log)

**Comment by stsp** [comment]
Please use `-D9+vX` log.

**Comment by bpranoto** [comment]
- I don't load any mouse driver, it's a keyboard only system. 
- Yes, I didn't have libsdl2-dev. I install it now.
- Doing git pull, and run `make deb` , it fails and throw an error:
       `dpkg-checkbuilddeps: error: Unmet build dependencies: fdpp`

**Comment by bpranoto** [comment]
Ok, I see your email about fdpp. Installing fpdd from ppa:dosemu2/ppa now...

**Comment by stsp** [comment]
> I don't load any mouse driver, it's a keyboard only system.

Hmm. Then it would be very interesting to
find out why pasting is in effect.

> Ok, I see your email about fdpp. Installing fpdd from ppa:dosemu2/ppa now...

Thank you!
I hope not too many people do "make deb"
actually, as this PPA provides the daily builds
of dosemu2. "make deb" is for developers.
I think users building from git, should just do
`make ; sudo make install` instead.
By the way, if you did `make deb`, how could
you miss the libsdl2-dev dep? The build should
have failed without it too.

**Comment by stsp** [comment]
> Sorry, the mouse works well in my dosemu. But MultiEdit for dos is not mouse aware....

This doesn't matter.
Mouse copy/pasting happens without any
interaction from DOS side. You can select
and copy any text screen, no matter if the
prog is mouse aware or not.

**Comment by bpranoto** [comment]
On Sun, Sep 9, 2018 at 11:08 PM Stas Sergeev <notifications@github.com>
wrote

> By the way, if you did make deb, how could
> you miss the libsdl2-dev dep? The build should
> have failed without it too.
>

To be honest, may be I had it before. I just run apt install libsdl2-dev
and and the package was downloaded and installed. It is 00:43 am now in my
place... :)

There is no crash yet since I rebuilt dosemu2, I will run dosemu2 with -S
and -D9+v from now on, so whenever I get the crash again I can post the log
file here. Thank you very much

**Comment by stsp** [comment]
> I will run dosemu2 with -S

No, `-S` is default.
You need to run `dosemu -X` to reproduce the
crash now, after you rebuilt dosemu with SDL.

**Comment by bpranoto** [comment]
> No, -S is default.

This is the boot.log when I run dosemu without any parameters:

```
VID: initializing video X
X: X_init

```
...and this is the log when I call dosemu -S:

```
VID: initializing video sdl
VID: SDL plugin initialization completed

```
so in my system, the default is -X ?

By the way there is always a warning: 

`ERROR: you appear to have unpatched vde`

How to get the pached vde?

**Comment by bpranoto** [comment]
Just get a crash...
[boot.log](https://github.com/stsp/dosemu2/files/2365963/boot.log)

**Comment by bpranoto** [comment]
sorry, please ignore, it still used old version of dosemu2...

**Comment by stsp** [comment]
> so in my system, the default is -X ?

Are you using a custom X font?
Since our SDL code doesn't support custom
fonts, this brings you back to X.

> How to get the pached vde?

Unfortunately I don't know.
Some distros applied my patches, but at
large vde is dead. I think I should just silence
down this error. :(

**Comment by stsp** [comment]
> sorry, please ignore, it still used old version of dosemu2...

Worse, its even w/o debug info.
Make sure to get debug info in (in case of
`make deb` by installing the -dbgsym)

**Comment by stsp** [comment]
> By the way there is always a warning:

Hm, wait a moment, is the warning on console or
in the log? Looking at the code, it seems it shouldn't
be printed on console.

**Comment by bpranoto** [comment]
>
> Hm, wait a moment, is the warning on console or
> in the log? Looking at the code, it seems it shouldn't
> be printed on console.
>

It is printed on console...

**Comment by bpranoto** [comment]
>> so in my system, the default is -X ?

> Are you using a custom X font?
> Since our SDL code doesn't support custom fonts, this brings you back to X.
>

in my dosemu.conf:

`$_X_font = "vga11x19"`

both dosemu -X and dosemu -S work well with this font setting

**Comment by stsp** [comment]
Have you altered the default `$_vnet=` setting?
Please attach the `-D9+cP` log.

**Comment by stsp** [comment]
Umm, wait, can reproduce on ubuntu...

**Comment by bpranoto** [comment]
Aha, get the crash again. This time the log looks good.....
[boot.log](https://github.com/stsp/dosemu2/files/2367069/boot.log)

**Comment by stsp** [comment]
Error msg should now be fixed.
Have you found any pattern in reproducing the
crash? Does it have to do with the mouse pasting
does it never happen with SDL?

**Comment by stsp** [comment]
Too many variables are optimized out.
Please re-build as follows:
`CFLAGS=-O0 ./default-configure -d`

**Comment by bpranoto** [comment]
> Have you found any pattern in reproducing the crash?

No, last time I just type out fast

> Does it have to do with the mouse pasting

No, ...may be somehow my finger hit the touchpad of my notebook, I am not sure..

> does it never happen with SDL?

I don't now, I usually don't care whether it runs with X or SDL... I'll switch to sdl, let's see whether it crashes or not...

**Comment by stsp** [comment]
Yes, I think its good enough,
Try to capture the log.
Thanks.

**Comment by bpranoto** [comment]
It has been 2 days and I still don't get a crash... Was it because of the compiler optimization?

**Comment by stsp** [comment]
Yes, the race condition can come and go
depending on an optimization. And an X
code uses threading more heavily than the
SDL code, and it got much fewer testing.

**Comment by stsp** [comment]
Should now be fixed.

**Comment by bpranoto** [comment]
Thanks.
