### ISSUE TITLE
fdpp/install integration

### ISSUE THREAD

**Issue by bolle732** [stsp/dosemu2#712]
There are use cases, where the install process of DOSEMU2 folders, files and links interfere with a custom setup.

For example, when setting up a custom setup by hand and having an error in it, DOSEMU2 starts the install process and can mess up the custom setup. This error can be due to wrong configuration or not to be compliant to what DOSEMU2 expect to be his way of system files and folders.

To protect an advanced user from possible side effects by the install process, an option to disable install should be implemented. I think, the best way would be a command line switch to `dosemu` / `dosemu.bin`. This option should not be set by default.

Additional, a warning to the user could be displayed / logged. Something like: "You're on your own foot!"

**Comment by stsp** [comment]
> Additional, a warning to the user could be displayed / logged. Something like: "You're on your own foot!"

The problem is not to warn the user, but
that he will inevitably forget to add that option
when he did the setup mistake.
If dosemu's install procedure corrupts any
of your custom files - _this_ is what should
be fixed. dosemu1 didn't hesitate to remove
and re-install things, but dosemu2 respects
user's data. So any overwriteing problems
should be reported and dealt with.

**Comment by bolle732** [comment]
Yes, you can always forget setting this option. But it's the fault of the _advanced_ user counting on this. Personally, I have always a start script with the needed options. So I should never forget about it.

We saw a lot of changes in the install process. And there may be others in the future too. I wan't to protect my setups from possible side effects due to changes in the layout of DOSEMU2. For me, a custom setup is like the users data, and it should not be touched.

This is in no way meant to prevent fixing errors / problems in the install process of DOSEMU2.

**Comment by andrewbird** [comment]
I know I'm not your usual user, but I have adopted the procedure of using an `--Fimagedir` so that dosemu{,2} can do whatever it likes in in ~/.dosemu without it concerning me. My local test-imagedir will get removed and recreated by myself often and I'd rather dosemu didn't 'fix' things in there for me. I noticed one of your commits earlier https://github.com/stsp/dosemu2/commit/d3245c4e0b6a2b21303ccb21f4e2dd1544d3ffab now supports installing into the `--Fimagedir`. I didn't see any problem with that yet (perhaps because Dosemu can't find the files to install), but a --PleaseDontInstall might be a nice companion?

**Comment by stsp** [comment]
> For me, a custom setup is like the users data, and it should not be touched.

Indeed. If it ever touched your file, this should
be reported. No matter how the install process
changes, it should not touch your files.
But guarding this with some otherwise useless
option, looks useless. You can't trust this option
any better than you trust me. :) So if I tell you
dosemu2 is not going to touch your files, the
otherwise may only happen because of a bug.
But the option can also suddenly became ignored
because of a bug. If you _really_ insist on protecting
your files, then you need to remove the write permission
from them. Then you trust linux developers rather
than me, and definitely they produce fewer bugs. :)

> --PleaseDontInstall might be a nice companion?

There should be no cases where dosemu2 corrupts
any of your files. As @bolle732 said, install can only
"annoy" you in case of a setup mistake on your side.
I wonder why you assume the setup mistake can happen,
but forgetting to specify this strange option - can't?
If you may setup mistakes, then you can as well forget
any option, and we need to make sure nothing bad
happens _even in this case_.

**Comment by stsp** [comment]
We can instead have some diagnostic
option that will write if your setup is valid
and what DOS will be booted (or install
started), and then it exits.
In this case you'll be able to script the option
you ask for. And this would be otherwise useful
too.

**Comment by bolle732** [comment]
The diagnostic / test / dry mode is a good idea

**Comment by stsp** [comment]
> In my eyes, it would be difficult to detect all possible combinations
> to decide if the install process should be started or not.

But this difficulty is already dealt with in fatfs-boot
mode. We (mostly Andrew) add the boot procedure
separately for every new DOS. We can't have it otherwise
when you just have the DOS files on the host FS and
no boot sector for them. So unless we know the
configuration is valid, we can't boot. When we know
it is, we take the needed boot files, put them to their
expected locations on the drive, and generate the
boot sector. So basically we load every DOS by hands.
We need to be aware of all possible boot combinations.
Its a pure illusion for the user that he can put some
new DOS to C: and try to boot it. He thinks so only
because Andrew already reverse-engineered the
needed boot-sector code.

> Or are you thinking on it as a self healing process in case the user deleted a system file / link ?

Yes, if boot fails, the attempt should be made to
recover and boot at least something else. But this
attempt is non-intrusive, should not touch user's
files.

**Comment by stsp** [comment]
OK, I think I know how to solve this all together.
Just give me a few days.

**Comment by bolle732** [comment]
> Yes, if boot fails, the attempt should be made to
> recover and boot at least something else. But this
> attempt is non-intrusive, should not touch user's
> files.

For the normal user, it's a good thing. For testing different combinations by advanced users not so much. I had it sometimes, that only some files / folders / links has been created and the boot still failed.

For me it seems, that already existing files are not verified if they fit with the currently existing ones. This could be very difficult.

If something else boots, this could be irritating.

**Comment by stsp** [comment]
I'll code a definite solution to all this a bit later.
For a while I forgot that altering --Fimagedir is
not the same as altering `$-hdimage`, and this
difference can very well be used.

**Comment by bolle732** [comment]
I / we would appreciate this very much.

For me, it's really not urgent. Take the time when you find you have it.

**Comment by stsp** [comment]
Should now be fixed.
@bolle732, @andrewbird could you please check
if this works properly for your setups?
Now you can relocate drive C with `--Fdrive_c`, and
install will not touch it. You must not change
`--Fimagedir` and `$_hdimage` when doing so.
Please try.

**Comment by andrewbird** [comment]
I didn't try `--Fdrive_c` as for testing I need to control the other drives too, but `--Fimagedir` with various settings of `$_hdimage` still works for me, so I guess that's good news.

**Comment by stsp** [comment]
Of course you don't expect me to keep
this unattended drive possibility forever.
Or maybe you do.
I tried to solve this in a peaceful manner. :)

**Comment by stsp** [comment]
I think this unattended booting is now gone.

**Comment by stsp** [comment]
> I think this unattended booting is now gone.

... except that `FDPP_KERNEL_DIR` still provides
the loop-hole... So I think only @bolle732 's setup
stopped working with the latest changes, but not
@andrewbird 's one. That's crazy. :)

**Comment by andrewbird** [comment]
You'll have to try harder :smile:

**Comment by stsp** [comment]
> You'll have to try harder smile

I can eg check if `FDPP_KERNEL_DIR` is not
within hdimage path, or something like that, but
this can be easily classified as the intentionally
malicious code. Right now I don't see any obvious
possibility to defeat this w/o intentionally malicious
code, but I'll have a think. :)

**Comment by bolle732** [comment]
> I didn't try `--Fdrive_c` as for testing I need to control the other drives too, but `--Fimagedir` with various settings of `$_hdimage` still works for me, so I guess that's good news.

The same applies to me with the latest git. It still works with the unaltered custom setups. I'll have to try the new flag later.

**Comment by stsp** [comment]
dosemu2 found a system-wide comcom32
install and assumes you are booting it.
I'll see about making the detection more
precise.
Ill need to fix FDPP_KERNEL_DIR
(although currently it works for me),
but why not to use drive C, and if you
need more, create it with DOSDRIVE_XTRA, or with lredir2?

**Comment by andrewbird** [comment]
Yes, I'd forgotten that I'd tried to use comcom earlier, so placed it where dosemu might find it. I've removed it now.. Unfortunately it doesn't boot but the messasges are different.
~~~
ajb@polly:/clients/common/dosemu2.git$ ./runstandalonetest.sh 

env FDPP_KERNEL_DIR=test-imagedir/dXXXXs/c ${GDB} bin/dosemu.bin \
	-n -f test-imagedir/dosemu.conf -D+dRWD -o test.log \
	--Flibdir test-libdir --Fimagedir test-imagedir \
	${GDB_DOSEMU_ARGS}
+ env FDPP_KERNEL_DIR=test-imagedir/dXXXXs/c bin/dosemu.bin -n -f test-imagedir/dosemu.conf -D+dRWD -o test.log --Flibdir test-libdir --Fimagedir test-imagedir
ERROR: Neither FreeDOS nor comcom32 installation found.
Use DOSEMU2_FREEDOS_DIR env var to specify alternative location.
ERROR: dosemu2 commands not found at /clients/common/dosemu2.git/test-libdir/dosemu2-cmds-0.2
ERROR: Your fluidsynth is too old and soundfonts not found
ERROR: alsa_midi (ALSA lib): rawmidi_hw.c:233:(snd_rawmidi_hw_open) : No such file or directory open /dev/snd/midiC0D0 failed
ERROR: Drive unbootable, exiting
~~~
~~~
ajb@polly:/clients/common/dosemu2.git$ find test-imagedir/dXXXXs/
test-imagedir/dXXXXs/
test-imagedir/dXXXXs/c
test-imagedir/dXXXXs/c/mfsfcbr1.S
test-imagedir/dXXXXs/c/autoexec.bat
test-imagedir/dXXXXs/c/version.bat
test-imagedir/dXXXXs/c/fdppkrnl.sys
test-imagedir/dXXXXs/c/mfsfcbr1.com.elf
test-imagedir/dXXXXs/c/config.sys
test-imagedir/dXXXXs/c/mfsfcbr1.com
test-imagedir/dXXXXs/c/test_mfs.bat
test-imagedir/dXXXXs/c/command.com
test-imagedir/dXXXXs/c/mfsfcbr1.o
test-imagedir/dXXXXs/c/dosemu
test-imagedir/dXXXXs/c/dosemu/exitemu.com
test-imagedir/dXXXXs/c/dosemu/speed.com
test-imagedir/dXXXXs/c/dosemu/emumouse.com
test-imagedir/dXXXXs/c/dosemu/unix.com
test-imagedir/dXXXXs/c/dosemu/dosdbg.com
test-imagedir/dXXXXs/c/dosemu/eject.com
test-imagedir/dXXXXs/c/dosemu/system.com
test-imagedir/dXXXXs/c/dosemu/blaster.com
test-imagedir/dXXXXs/c/dosemu/sound.com
test-imagedir/dXXXXs/c/dosemu/isemu.com
test-imagedir/dXXXXs/c/dosemu/cdrom.sys
test-imagedir/dXXXXs/c/dosemu/generic.com
test-imagedir/dXXXXs/c/dosemu/umb.sys
test-imagedir/dXXXXs/c/dosemu/emufs.sys
test-imagedir/dXXXXs/c/dosemu/xmode.com
test-imagedir/dXXXXs/c/dosemu/aspi.sys
test-imagedir/dXXXXs/c/dosemu/dpmi.com
test-imagedir/dXXXXs/c/dosemu/lredir2.com
test-imagedir/dXXXXs/c/dosemu/fossil.com
test-imagedir/dXXXXs/c/dosemu/ems.sys
test-imagedir/dXXXXs/c/dosemu/lredir.com
test-imagedir/dXXXXs/d
test-imagedir/dXXXXs/d/testa.bat
~~~
~~~
ajb@polly:/clients/common/dosemu2.git$ cat test-imagedir/dosemu.conf 
$_lpt1 = ""
$_hdimage = "dXXXXs/c:hdtype1 dXXXXs/d:hdtype1"
$_floppy_a = ""
$_bootdrive = "c"
~~~

The thing is I test more than just MFS, for instance, I'm doing FCB tests on FATFS too so mapping drives with lredir etc won't work for me. I already uncovered that FreeDOS and hence FDPP are broken with FCB wildcards in the OS proper, not just redirector. Creating drives in this way gives me the flexibility I need.
I do understand that that you're trying to move to a more Dosbox working out of the box style installation for the casual or first time user though, which is great. I can live with FDPP not working for my test cases as I only recently started testing it anyway, as long as the standard DOSes keep working with `--Fimagedir` and `$_hdimage`?

**Comment by stsp** [comment]
But $_hdimage provides you with the
great flexibility. You can add new dirs
to it without removing the old ones, and
all fatfs drives will be created. So why
to change Fimagedir?

**Comment by andrewbird** [comment]
Because I delete and repopulate the test directory before every test so that a prior test state or rogue user files can have no bearing on the current test. I don't want that going on in my home directory, or subdirectory of it.

**Comment by stsp** [comment]
You can do the same with the files and
dirs that you _added_ to `$_hdimage`.
They do not have to be in your home
dir, they can be anywhere. `$_hdimage`
allows you all that and above.

**Comment by stsp** [comment]
`$_hdimage = "drives/* /tmp/my_tests/*` and that's
all! You can now even overtake the drive C too.

**Comment by andrewbird** [comment]
And dosemu won't ever look back at my `~/.dosemu` ? If so, I can live with absolute pathing. I'll give it a try.

**Comment by stsp** [comment]
> And dosemu won't ever look back at my ~/.dosemu ?

Why not? It will use it for boot, but all drives
except C there are read-only, so you won't
notice any differences.

**Comment by andrewbird** [comment]
But I don't want to boot or reference anything from anything outside my test-imagedir. I guess that's what I'm seeing.
~~~
ajb@polly:/clients/common/dosemu2.git$ cat test-imagedir/dosemu.conf
$_lpt1 = ""
$_hdimage = "/clients/common/dosemu2.git/dXXXXs/c:hdtype1 /clients/common/dosemu2.git/dXXXXs/d:hdtype1"
$_floppy_a = ""
$_bootdrive = "c"
~~~
~~~
bin/dosemu.bin \
	-n -f test-imagedir/dosemu.conf -D+dRWD -o test.log \
	--Flibdir test-libdir
+ bin/dosemu.bin -n -f test-imagedir/dosemu.conf -D+dRWD -o test.log --Flibdir test-libdir
ERROR: Neither FreeDOS nor comcom32 installation found.
Use DOSEMU2_FREEDOS_DIR env var to specify alternative location.
ERROR: No system files found at /clients/common/dosemu2.git/test-libdir/fdboot
ERROR: dosemu2 commands not found at /clients/common/dosemu2.git/test-libdir/dosemu2-cmds-0.2
ERROR: Your fluidsynth is too old and soundfonts not found
ERROR: alsa_midi (ALSA lib): rawmidi_hw.c:233:(snd_rawmidi_hw_open) : No such file or directory open /dev/snd/midiC0D0 failed
ERROR: Drive C not defined, can't boot!

#env FDPP_KERNEL_DIR=test-imagedir/dXXXXs/c ${GDB} bin/dosemu.bin \
#	-n -f test-imagedir/dosemu.conf -D+dRWD -o test.log \
#	--Flibdir test-libdir --Fimagedir test-imagedir \
#	${GDB_DOSEMU_ARGS}

~~~

**Comment by stsp** [comment]
> But I don't want to boot or reference anything from anything outside my test-imagedir.

Not a problem, use `--Fimagedir` to alter the main dir,
and use `$_hdimage` to _add_ drives to it (either with
absolute or relative pathes).

**Comment by andrewbird** [comment]
I added this little patch that shows that logic is looking in the right place, but not finding the boot files
```C
ajb@polly:/clients/common/dosemu2.git$ git diff
diff --git a/src/emu.c b/src/emu.c
index 202cf5122..dec67c543 100644
--- a/src/emu.c
+++ b/src/emu.c
@@ -221,7 +221,7 @@ void boot(void)
     } else {
        if (dp->type == DIR_TYPE) {
            if (!disk_is_bootable(dp) || !disk_validate_boot_part(dp)) {
-               error("Drive unbootable, exiting\n");
+               error("Drive (%s) unbootable, exiting\n",  dp->dev_name);
                leavedos(16);
            }
        }
```
~~~
ajb@polly:/clients/common/dosemu2.git$ ./runstandalonetest.sh 

env FDPP_KERNEL_DIR=test-imagedir/dXXXXs/c ${GDB} bin/dosemu.bin \
	-n -f test-imagedir/dosemu.conf -D+dRWD -o test.log \
	--Flibdir test-libdir --Fimagedir test-imagedir \
	${GDB_DOSEMU_ARGS}
+ env FDPP_KERNEL_DIR=test-imagedir/dXXXXs/c bin/dosemu.bin -n -f test-imagedir/dosemu.conf -D+dRWD -o test.log --Flibdir test-libdir --Fimagedir test-imagedir
ERROR: Neither FreeDOS nor comcom32 installation found.
Use DOSEMU2_FREEDOS_DIR env var to specify alternative location.
ERROR: dosemu2 commands not found at /clients/common/dosemu2.git/test-libdir/dosemu2-cmds-0.2
ERROR: Your fluidsynth is too old and soundfonts not found
ERROR: alsa_midi (ALSA lib): rawmidi_hw.c:233:(snd_rawmidi_hw_open) : No such file or directory open /dev/snd/midiC0D0 failed
ERROR: Drive (/clients/common/dosemu2.git/test-imagedir/dXXXXs/c) unbootable, exiting

ajb@polly:/clients/common/dosemu2.git$ ls /clients/common/dosemu2.git/test-imagedir/dXXXXs/c
autoexec.bat  command.com  config.sys  dosemu  fdppkrnl.sys  mfsfcbr1.com  mfsfcbr1.com.elf  mfsfcbr1.o  mfsfcbr1.S  test_mfs.bat  version.bat
ajb@polly:/clients/common/dosemu2.git$ 
~~~

**Comment by stsp** [comment]
Try pointing `FDPP_KERNEL_DIR` to fdpp build
dir (that also contains fdppkrnl.sys) and `DOSEMU2_FREEDOS_DIR`
to comcom32.

**Comment by stsp** [comment]
I booted your test-case as follows:
```
bin/dosemu.bin -n -f test-imagedir/dosemu.conf -D+dRWD -o test.log --Fimagedir test-imagedir --Fdrive_c test-imagedir/dXXXXs/c
```

I do not use `FDPP_KERNEL_DIR`/`DOSEMU2_FREEDOS_DIR`
as I have fdpp/comcom32 installed. But they still work as expected.

**Comment by stsp** [comment]
I mean, I fixed a few bugs and booted your test-case
that way. Please update.

**Comment by stsp** [comment]
`$_hdimage = "drives/* dXXXXs/*"`

**Comment by andrewbird** [comment]
> $_hdimage = "drives/* dXXXXs/*"

What's the reasoning behind this, is it necessary (I did try it but it didn't help me)? The only reason I have dXXXXs is because until recently even if --Fimagedir was specified dosemu was still finding drives under ~/.dosemu

It still doesn't boot for me, perhaps it works for you because you have fdpp/comcom32 installed? I'll wait until the dust settles on your current set of changes and use FreeDOS for testing comcom32 for now. Thanks for your help.

**Comment by stsp** [comment]
Also you need to disable $_bootdrive

**Comment by stsp** [comment]
dosemu2 now errors a lot, so if you
used --Flibdir/vars correctly, youll see
the result (of no errors). It should be
able to find all its components.

**Comment by stsp** [comment]
> What's the reasoning behind this, is it necessary

This is no longer necessary.
So I run a fully self-contained dosemu2 install this way:
`bin/dosemu.bin --Fimagedir test-imagedir --Fdrive_c test-imagedir/dXXXXs/c --Flibdir test-libdir`
In `test-libdir` I have the content of `/usr/local/share/dosemu`.
If you don't have fdpp/comcom32 installed, you need to
use the env vars.
